In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame({'col1':[0,9,8,7],
              'col2':[6,5,4,3],
              'col3':"welcome to  google colab "})

col1  col2                       col3
0     0     6  welcome to  google colab 
1     9     5  welcome to  google colab 
2     8     4  welcome to  google colab 
3     7     3  welcome to  google colab

In [ ]:
"welcome to  google colab".split()

['welcome', 'to', 'google', 'colab']

In [ ]:
df=pd.DataFrame({'col1':[0,9,8,7],
              'col2':[6,5,4,3],
              'col3':"welcome to  google colab".split()})
df

col1  col2     col3
0     0     6  welcome
1     9     5       to
2     8     4   google
3     7     3    colab

In [ ]:
df['col4']=df['col1']**2
df

col1  col2     col3  col4
0     0     6  welcome     0
1     9     5       to    81
2     8     4   google    64
3     7     3    colab    49

In [ ]:
df['col5']=df['col3'].str[0]
df

col1  col2     col3  col4 col5
0     0     6  welcome     0    w
1     9     5       to    81    t
2     8     4   google    64    g
3     7     3    colab    49    c

In [ ]:
def test(a):
  return a**3

In [ ]:
df['col6']=df['col2'].apply(test)
df

col1  col2     col3  col4 col5  col6
0     0     6  welcome     0    w   216
1     9     5       to    81    t   125
2     8     4   google    64    g    64
3     7     3    colab    49    c    27

In [ ]:
def test1(a):
  if a=="c":
    return "collab"

  else:
      return "No"

In [ ]:
df['col7']=df['col5'].apply(test1)
df

col1  col2     col3  col4 col5  col6    col7
0     0     6  welcome     0    w   216      No
1     9     5       to    81    t   125      No
2     8     4   google    64    g    64      No
3     7     3    colab    49    c    27  collab

In [ ]:
lambda a:"yes" if a=='c' else "no"

<function __main__.<lambda>(a)>

In [ ]:
df['col8'] = df['col5'].apply(lambda a : "yes" if a == 'c' else "no")

In [ ]:
df

col1  col2     col3  col4 col5  col6    col7 col8
0     0     6  welcome     0    w   216      No   no
1     9     5       to    81    t   125      No   no
2     8     4   google    64    g    64      No   no
3     7     3    colab    49    c    27  collab  yes

In [ ]:
df['col9']=df['col3'].str.len()
df

col1  col2     col3  col4 col5  col6    col7 col8  col9
0     0     6  welcome     0    w   216      No   no     7
1     9     5       to    81    t   125      No   no     2
2     8     4   google    64    g    64      No   no     6
3     7     3    colab    49    c    27  collab  yes     5

In [ ]:
df['col9']=df['col3'].apply(len)
df

col1  col2     col3  col4 col5  col6    col7 col8  col9
0     0     6  welcome     0    w   216      No   no     7
1     9     5       to    81    t   125      No   no     2
2     8     4   google    64    g    64      No   no     6
3     7     3    colab    49    c    27  collab  yes     5

In [ ]:
def test2(a):
  if type(a)==str:
    return len(a)
  else:
    return "no"

In [ ]:
df['vcol9'] = df['col3'].apply(test2)
df

col1  col2     col3  col4 col5  col6    col7 col8  col9  vcol9
0     0     6  welcome     0    w   216      No   no     7      7
1     9     5       to    81    t   125      No   no     2      2
2     8     4   google    64    g    64      No   no     6      6
3     7     3    colab    49    c    27  collab  yes     5      5

In [ ]:
import math

In [ ]:
df['col10']=df['col2'].apply(math.log)
df

col1  col2     col3  col4 col5  col6    col7 col8  col9  vcol9     col10
0     0     6  welcome     0    w   216      No   no     7      7  1.791759
1     9     5       to    81    t   125      No   no     2      2  1.609438
2     8     4   google    64    g    64      No   no     6      6  1.386294
3     7     3    colab    49    c    27  collab  yes     5      5  1.098612

In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3,4,5,6,7,8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
type(np.array([1,2,3,4,5,6,7,8,9]))

numpy.ndarray

In [ ]:
np.array([1,2,3,4,5,6.0,4.5])

array([1. , 2. , 3. , 4. , 5. , 6. , 4.5])

In [ ]:
np.array([[1,3],[3,4
                 ]])

array([[1, 3],
       [3, 4]])

In [ ]:
np.array([1,2,3], ndmin = 3)

array([[[1, 2, 3]]])

In [ ]:
np.array([1,2,3], ndmin = 3)

array([[[1, 2, 3]]])

In [ ]:
np.array([1,2,3], dtype= complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
arr =   np.array([(1,2),(2,3)])
arr[0]

array([1, 2])

In [ ]:
arr[0][1]

np.int64(2)

In [ ]:
import pandas as pd

import numpy as np

In [ ]:
arr= np.array([[1,3],[3,4]])
arr

array([[1, 3],
       [3, 4]])

In [ ]:
a=arr
b=np.copy(arr)
arr[0]

array([1, 3])

In [ ]:
arr[0][0]

np.int64(1)

In [ ]:
arr[0][1]

np.int64(3)

In [ ]:
arr[0][0]=68
a

array([[68,  3],
       [ 3,  4]])

In [ ]:
arr

array([[68,  3],
       [ 3,  4]])

In [ ]:
b

array([[1, 3],
       [3, 4]])

In [ ]:
m=[1,6,7,8,9]
m[-1]

9

In [ ]:
m[::-1]

[9, 8, 7, 6, 1]

In [ ]:
arr[0:100]

array([[68,  3],
       [ 3,  4]])

In [ ]:
for i in arr:
  print(i)

[68  3]
[3 4]


In [ ]:
np.fromfunction(lambda i,j:i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [ ]:
m=[7,8,9,4,76]
arr=np.array(m)
arr

array([ 7,  8,  9,  4, 76])

In [ ]:
arr1=np.array([[1,2,3,4,5],[2,3,4,5,6]])
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr1.ndim

2

In [ ]:
arr1.size

10

In [ ]:
arr.size

5

In [ ]:
range(6)

range(0, 6)

In [ ]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [ ]:
np.arange(6.6)

array([0., 1., 2., 3., 4., 5., 6.])

In [ ]:
np.arange(6.6,9,0.3)

array([6.6, 6.9, 7.2, 7.5, 7.8, 8.1, 8.4, 8.7, 9. ])

In [ ]:
np.arange(6.6,9,-3)

array([], dtype=float64)

In [ ]:
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

In [ ]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.zeros(3, dtype = complex)

array([0.+0.j, 0.+0.j, 0.+0.j])

In [ ]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
np.ones((2,3,2))+ 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [ ]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [ ]:
np.random.rand(4)

array([0.48237815, 0.47345628, 0.1427474 , 0.89243376])

In [ ]:
np.random.randn(4)

array([ 0.51033962,  1.06149893, -1.60023264,  1.21888632])

In [ ]:
np.random.randn(2,3)

array([[ 0.39932095,  0.13655067,  0.69684557],
       [-0.34408978, -0.53910836,  0.33007039]])

In [ ]:
np.random.randn(2,2,3)

array([[[ 0.26156399, -1.14592255, -0.50380229],
        [ 0.061965  ,  0.7603928 , -0.67099315]],

       [[ 0.22018144, -0.62606621, -0.3814234 ],
        [ 0.90479831,  0.58350566,  0.12463142]]])

In [ ]:
np.random.randint(5,6)

5

In [ ]:
arr = np.random.randint(5,60,(4,4))
np.random.randint(3,90,(2,3,4))

array([[[79, 54, 75, 56],
        [11, 84, 33, 59],
        [34, 43,  6, 37]],

       [[53, 35, 65, 87],
        [28, 73, 42, 15],
        [ 7,  8, 60, 20]]])

In [ ]:
arr

array([[49, 50, 44, 17],
       [58, 41, 16, 27],
       [49,  5,  9, 22],
       [46, 50, 50, 46]])

In [ ]:
arr.max()

np.int64(58)

In [ ]:
arr.min()

np.int64(5)

In [ ]:
arr>10

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True, False, False,  True],
       [ True,  True,  True,  True]])

In [ ]:
arr[arr>10]

array([49, 50, 44, 17, 58, 41, 16, 27, 49, 22, 46, 50, 50, 46])

In [ ]:
arr*arr

array([[2401, 2500, 1936,  289],
       [3364, 1681,  256,  729],
       [2401,   25,   81,  484],
       [2116, 2500, 2500, 2116]])

In [ ]:
pd.DataFrame(np.random.randn(10,4))

0         1         2         3
0 -0.221411  0.489056  1.425449 -0.263191
1 -0.024005 -0.223163 -0.157505 -1.688116
2 -0.907423 -0.714103 -0.956452  0.214208
3  0.326412 -1.327587 -1.161695 -0.242512
4  1.159604 -0.107993 -0.601665  0.880636
5 -1.882708  0.192955 -1.809644 -0.729103
6 -0.421635 -0.055575  0.222369  0.134571
7  0.269065  1.862143  2.725258 -0.655386
8 -0.596373 -0.404614 -1.969644  1.808050
9 -0.330349  1.122291  0.542532  0.219484

In [ ]:
pd.DataFrame(np.random.randn(10,4),index = pd.date_range('2021-07-18',periods= 10 ))

0         1         2         3
2021-07-18 -1.271302 -1.172039  0.763495 -0.225721
2021-07-19 -1.106999  0.717438  0.227386  0.979672
2021-07-20 -0.042724 -1.163575  0.220584 -0.210814
2021-07-21  0.029020 -0.725999 -0.427514  0.378879
2021-07-22  0.824468 -0.316855  0.396176 -0.764593
2021-07-23 -0.712434 -0.301282  0.485135 -0.133404
2021-07-24 -2.067094  1.304561  0.824727 -0.244020
2021-07-25 -1.086278  1.145694 -0.298143  0.590310
2021-07-26 -1.544905  0.634816 -0.802102 -2.045366
2021-07-27 -1.317013  0.934558 -1.198152  1.365242

In [ ]:
pd.DataFrame(np.random.randn(10,4),index = pd.date_range('2021-07-18',periods= 10 ))

0         1         2         3
2021-07-18  1.602252 -0.520235  0.973458  1.956924
2021-07-19  1.020473  0.677986  0.918823 -1.589913
2021-07-20  0.725449  0.209693  1.203124 -0.324905
2021-07-21 -0.043862  2.164293  0.456524  1.769297
2021-07-22  0.632534 -0.106205 -0.042884 -0.151299
2021-07-23  0.720282  0.029026 -1.778615 -0.545129
2021-07-24  2.117359  0.247602  1.667669  0.377157
2021-07-25 -0.875973 -0.973482 -0.622807  1.564884
2021-07-26  0.082406 -0.411595 -0.838015  0.875129
2021-07-27  0.089972  0.074884 -3.089081  1.224076

In [ ]:
df = pd.DataFrame(np.random.randn(10,4),index = pd.date_range('2021-07-18',periods= 10 ),columns = ['a','b','c','d'])

In [ ]:
df

a         b         c         d
2021-07-18  0.123235 -1.093963 -2.163838  2.048671
2021-07-19 -2.252909 -0.567982 -0.911832  0.278311
2021-07-20 -1.861192 -1.463834 -0.912236 -1.891821
2021-07-21 -1.714156  0.109570  0.209562  0.324279
2021-07-22  0.467094 -0.614718 -0.692975  0.126483
2021-07-23 -0.130966 -0.548501 -0.317567 -0.007447
2021-07-24  1.211756  0.700537 -0.745496  0.121002
2021-07-25  1.441358  0.236347 -1.937427  1.525336
2021-07-26 -0.681449  1.666328  0.090568 -1.159595
2021-07-27 -0.435490  0.583703 -0.842089  0.131570

In [ ]:
df['new'] = df['c'] + df['d']
df

a         b         c         d       new
2021-07-18  0.123235 -1.093963 -2.163838  2.048671 -0.115167
2021-07-19 -2.252909 -0.567982 -0.911832  0.278311 -0.633521
2021-07-20 -1.861192 -1.463834 -0.912236 -1.891821 -2.804057
2021-07-21 -1.714156  0.109570  0.209562  0.324279  0.533841
2021-07-22  0.467094 -0.614718 -0.692975  0.126483 -0.566492
2021-07-23 -0.130966 -0.548501 -0.317567 -0.007447 -0.325015
2021-07-24  1.211756  0.700537 -0.745496  0.121002 -0.624494
2021-07-25  1.441358  0.236347 -1.937427  1.525336 -0.412091
2021-07-26 -0.681449  1.666328  0.090568 -1.159595 -1.069027
2021-07-27 -0.435490  0.583703 -0.842089  0.131570 -0.710518

In [ ]:
def test(a):
  return a**2


In [ ]:
  df['square_d'] = df['d'].apply(test)
  df

a         b         c         d       new  square_d
2021-07-18  0.123235 -1.093963 -2.163838  2.048671 -0.115167  4.197051
2021-07-19 -2.252909 -0.567982 -0.911832  0.278311 -0.633521  0.077457
2021-07-20 -1.861192 -1.463834 -0.912236 -1.891821 -2.804057  3.578987
2021-07-21 -1.714156  0.109570  0.209562  0.324279  0.533841  0.105157
2021-07-22  0.467094 -0.614718 -0.692975  0.126483 -0.566492  0.015998
2021-07-23 -0.130966 -0.548501 -0.317567 -0.007447 -0.325015  0.000055
2021-07-24  1.211756  0.700537 -0.745496  0.121002 -0.624494  0.014642
2021-07-25  1.441358  0.236347 -1.937427  1.525336 -0.412091  2.326650
2021-07-26 -0.681449  1.666328  0.090568 -1.159595 -1.069027  1.344660
2021-07-27 -0.435490  0.583703 -0.842089  0.131570 -0.710518  0.017311